name: RestaurantManager.Interface CI/CD

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Production
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Build And Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_NICE_PLANT_082ECD603 }}
          action: "upload"
          production_branch: "master"
          app_location: "./RestaurantManager.Interface"
          output_location: "wwwroot"
          app_build_command: >
            dotnet publish -c Release -o ./publish &&
            mkdir -p ./publish/wwwroot &&
            echo '{"RestaurantManagerApiAddress":"https://restaurantmanagerapi-c9hwd2cwf9hka4an.spaincentral-01.azurewebsites.net/api/"}' > ./publish/wwwroot/appsettings.json